version: "3.5"

services:
  php-fpm:
    build:
      context: ./docker
      target: php-fpm
    volumes:
      - .:/app
    ports:
      - "9000:9000"
  web:
    image: nginx
    links:
      - php-fpm
    volumes:
      - .:/app
      - ./docker/nginx/fastcgi-params.conf:/etc/nginx/fastcgi-params.conf
      - ./docker/ssl/certs:/etc/ssl/certs/:ro
      - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "${NGINX_NO_SSL_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
