version: "3.4"


networks:
  app-tier:
    driver: bridge


services:

  php-fpm:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - .:/app

  web:
    image: nginx
    links:
      - php-fpm
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi-params.conf:/etc/nginx/fastcgi-params.conf
      - ./docker/ssl/certs:/etc/ssl/certs/:ro
    ports:
      - "8000:80"
      - "443:443"

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
