version: "3.4"
services:

  php:
    build:
      context: ./docker
      target: php
    volumes:
      - .:/var/www/html
  web:
    image: nginx
    links:
      - php
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi-params.conf:/etc/nginx/fastcgi-params.conf
      - ./docker/ssl/certs:/etc/ssl/certs/:ro
    ports:
      - "8000:80"
      - "443:443"
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
