version: "3.5"

services:
  php-fpm:
    build:
      context: ./docker
      target: php-fpm
    volumes:
      - .:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "9000:9000"
    extra_hosts:
      - host.docker.internal:host-gateway
  web:
    image: nginx
    env_file:
      - .env-docker
    links:
      - php-fpm
    volumes:
      - .:/app
      - ./docker/nginx/fastcgi-params.conf:/etc/nginx/fastcgi-params.conf
      - ./docker/ssl/certs:/etc/ssl/certs/:ro
      - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 8000:80
      - 443:443
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
